### ISSUE TITLE
Power support on the PCIe slot

### ISSUE THREAD

**Issue by galvesribeiro** [badger707/m920q-pcie-bifurcation#5]
Hello!

I know it is a bit of topic for this repo specifically but since @badger707 / @j4cbo / @frankol are dealing with the PCIe slot here, I wonder if you guys can shed a light on this...

I've searched around on how much power the motherboard is pushing on the M920q but without much luck but some other folks said on reddit that for sure it is not 70W even if I use the bigger 135W brick. I would like to try put a RTX 4000 or A4000 on that PCI slot but before I pull the trigger on buying one, do you guys know how much does this slot deliver?

Lenovo suggest use the Quadro T1000 which is 50W, so even if 70W is not delivered as is, do you guys think there is any chance a mod on the power circuitry could get us the 70W on the PCIe slot?

Another (not so elegant) alternative would be to find out if the GPU board has the traces to a power connector so we could solder it and connect to an external PSU similar to what we see with regular/more power hungry GPUs.

Thanks!

**Comment by j4cbo** [comment]
The schematic says the 12V rail is rated for 5.5 amps (66W), and the only significant loads on it are the PCIe header and the CPU fan. 70W is technically out-of-spec but might be OK in practice... if possible try to get some airflow over the power supply components.
<img width="670" alt="Screenshot 2024-04-14 at 12 47 48 PM" src="https://github.com/badger707/m920q-pcie-bifurcation/assets/537158/f00ef76a-a051-42da-a8b7-11c17f8dcd9e">

**Comment by galvesribeiro** [comment]
Hummm interesting. The thing is, from what I've read, the machine works with the 70W cards but they shutdown as soon as the GPU decides for a very few milliseconds to boost. The GPU clocks would be are 1450Mhz but Nvidia allows it to automatically boost to 2100Mhz+ very briefly when using the CUDA cores (i.e. running AI workloads). When that happen, as soon as it hit 1500Mhz it shutdown.

Not sure where could put an extra cooler there tho :/ 

Btw, you mentioned on your riser that you added a bulk converter to alleviate the load on the mobo rails. Would that help in this situation?

**Comment by j4cbo** [comment]
It would be a much more involved change. My riser uses 12V from the motherboard to provide 3.3 to the extra M.2s; but the DC/DC here is from the 20V input down to 12V, and there isn't a good way to access 20V off the motherboard that I can tell.

"TDP" is a tricky term... technically it means _thermal_ design power which is the maximum long-term average, but a device can exceed its TDP for short periods (turbo boost, etc). The limiting factor for these GPUs isn't thermal, it's short-term electrical load.
